spring.application.name=CatalogSystem
server.port = 8080
spring.data.mongodb.uri= mongodb://localhost:27017/feedback
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.mode=HTML
spring.thymeleaf.check-template-location=true